package juego;

public class Palabras {
	
	static final String [] futbol = {"RONALDO","IBRAHIMOVIC","BALE","RONALDINHO","KAKA","INIESTA","RIBERY","BALOTELLI",
			"LAMPARD","PIRLO","DROGBA","MESSI","ROBBEN","XAVI","MULLER","LUIS SUAREZ","VILLA","XABI",
			"EL SHAARAWY","HENRY","TORRES","TERRY","DAVID LUIZ","HAZARD","ETOO","VIDAL","DIEGO COSTA",
			"AGUERO","GUERRERO","MOTTA","MATA","RAMOS","FARFAN","BA","ALEXIS","DI MARIA","ALVES", "TEVEZ",
			"LAVEZZI","PATO","LLORENTE","PIQUE","ISCO","PIZARRO","MODRIC","ABATE","MEXES","PEPE","NEYMAR"}; //son 50
	static final  String [] ciudad = {"VITORIA","ALBACETE","ALICANTE","ALMERIA","OVIEDO","AVILA","BADAJOZ",
			"BARCELONA","BURGOS","CACERES","CADIZ","SANTANDER","CASTELLON","CIUDAD REAL","CORDOBA",
			"LA CORUÑA","CUENCA","GERONA","GRANADA","GUADALAJARA","SAN SABASTIAN","HUELVA","HUESCA",
			"PALMA","JAEN","LEON","LERIDA","LUGO","MADRID","MALAGA","MURCIA","PAMPLONA","ORENSE",
			"PALENCIA","LAS PALMAS","PONTEVEDRA","LOGROÑO","SALAMANCA","SEGOVIA","SEVILLA","SORIA",
			"TARRAGONA","SANTA CRUZ","TERUEL","TOLEDO","VALENCIA","VALLADOLID","BILBAO","ZAMORA",
			"ZARAGOZA"}; //son 50
	static final  String [] pelis = {"EL PADRINO","PULP FICTION","CADENA PERPETUA","LA VIDA ES BELLA","CIUDAD DE DIOS",
			"CASABLANCA","PSICOSIS","SIN PERDON","EL PIANISTA","INTOCABLE","LA HUELLA","SEVEN","CIUDADANO KEIN",
			"GRAN TORINO","BLADE RUNNER","EL RESPLANDOR","TAXI DRIVER","CASINO","MYSTIC RIVER","HAMLET",
			"ORIGEN","TOY STORY","BRAVEHEART","SCARFACE","UP","WALL E","LA MILLA VERDE","DJANGO","MATRIX",
			"GLADIATOR","AMELIE","BEN HUR","MEMENTO","EL REY LEON","LA VIDA DE BRIAN","NUEVE REINAS","INFILTRADOS",
			"CABARET","SHREK","TESIS","KILL BILL","CASINO","TORRENTE","TWISTER","LA VIDA DE PI","ARMAGEDON",
			"LA NIEBLA","TRAINING DAY","TED","THE CODE"}; //son 50
	static final  String [] aleato = {"RONALDO","IBRAHIMOVIC","BALE","RONALDINHO","KAKA","INIESTA","RIBERY","BALOTELLI",
			"LAMPARD","PIRLO","DROGBA","MESSI","ROBBEN","XAVI","MULLER","LUIS SUAREZ","VILLA","XABI",
			"EL SHAARAWY","HENRY","TORRES","TERRY","DAVID LUIZ","HAZARD","ETOO","VIDAL","DIEGO COSTA",
			"AGUERO","GUERRERO","MOTTA","MATA","RAMOS","FARFAN","BA","ALEXIS","DI MARIA","ALVES", "TEVEZ",
			"LAVEZZI","PATO","LLORENTE","PIQUE","ISCO","PIZARRO","MODRIC","ABATE","MEXES","PEPE","NEYMAR",
			"VITORIA","ALBACETE","ALICANTE","ALMERIA","OVIEDO","AVILA","BADAJOZ",
			"BARCELONA","BURGOS","CACERES","CADIZ","SANTANDER","CASTELLON","CIUDAD REAL","CORDOBA",
			"LA CORUÑA","CUENCA","GERONA","GRANADA","GUADALAJARA","SAN SABASTIAN","HUELVA","HUESCA",
			"PALMA","JAEN","LEON","LERIDA","LUGO","MADRID","MALAGA","MURCIA","PAMPLONA","ORENSE",
			"PALENCIA","LAS PALMAS","PONTEVEDRA","LOGROÑO","SALAMANCA","SEGOVIA","SEVILLA","SORIA",
			"TARRAGONA","SANTA CRUZ","TERUEL","TOLEDO","VALENCIA","VALLADOLID","BILBAO","ZAMORA",
			"ZARAGOZA","EL PADRINO","PULP FICTION","CADENA PERPETUA","LA VIDA ES BELLA","CIUDAD DE DIOS",
			"CASABLANCA","PSICOSIS","SIN PERDON","EL PIANISTA","INTOCABLE","LA HUELLA","SEVEN","CIUDADANO KEIN",
			"GRAN TORINO","BLADE RUNNER","EL RESPLANDOR","TAXI DRIVER","CASINO","MYSTIC RIVER","HAMLET",
			"ORIGEN","TOY STORY","BRAVEHEART","SCARFACE","UP","WALL E","LA MILLA VERDE","DJANGO","MATRIX",
			"GLADIATOR","AMELIE","BEN HUR","MEMENTO","EL REY LEON","LA VIDA DE BRIAN","NUEVE REINAS","INFILTRADOS",
			"CABARET","SHREK","TESIS","KILL BILL","CASINO","TORRENTE","TWISTER","LA VIDA DE PI","ARMAGEDON",
			"LA NIEBLA","TRAINING DAY","TED","THE CODE"};

}
